# Generated by Django 5.2.7 on 2025-11-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("image", "이미지 생성"),
                            ("audio", "음성 생성"),
                            ("thumbnail", "썸네일 생성"),
                            ("report", "리포트 생성"),
                        ],
                        max_length=20,
                        verbose_name="작업 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("processing", "처리중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("input_data", models.JSONField(default=dict, verbose_name="입력 데이터")),
                (
                    "result_data",
                    models.JSONField(blank=True, default=dict, verbose_name="결과 데이터"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="오류 메시지"),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Celery Task ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="시작일시"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료일시"),
                ),
            ],
            options={
                "verbose_name": "생성 작업",
                "verbose_name_plural": "생성 작업",
                "db_table": "generation_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(max_length=500, unique=True, verbose_name="저장 경로"),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="파일명")),
                ("mime_type", models.CharField(max_length=100, verbose_name="MIME 타입")),
                ("file_size", models.BigIntegerField(verbose_name="파일 크기 (bytes)")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "이미지"),
                            ("video", "비디오"),
                            ("audio", "오디오"),
                            ("document", "문서"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                        verbose_name="자산 유형",
                    ),
                ),
                (
                    "width",
                    models.IntegerField(blank=True, null=True, verbose_name="가로 크기"),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="세로 크기"),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="재생 시간 (초)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="추가 메타데이터"),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="공개 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
            ],
            options={
                "verbose_name": "미디어 자산",
                "verbose_name_plural": "미디어 자산",
                "db_table": "media_assets",
                "ordering": ["-created_at"],
            },
        ),
    ]
