# Generated by Django 5.2.7 on 2025-11-05 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="요청 사용자",
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_assets",
                to="organizations.organization",
                verbose_name="소속 조직",
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="업로드 사용자",
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="result_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_jobs",
                to="media.mediaasset",
                verbose_name="결과 미디어",
            ),
        ),
    ]
