# Generated by Django 5.2.7 on 2025-11-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="attempts",
            field=models.IntegerField(
                default=0, help_text="작업 시도 횟수 (재시도 포함)", verbose_name="시도 횟수"
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="scanned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="바이러스 스캔 일시"
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="sha256",
            field=models.CharField(
                blank=True,
                help_text="파일 무결성 검증용",
                max_length=64,
                null=True,
                verbose_name="SHA256 해시",
            ),
        ),
    ]
