# Generated by Django 5.2.8 on 2025-11-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0003_generationjob_attempts_mediaasset_scanned_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generationjob",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "이미지 생성 작업",
                "verbose_name_plural": "이미지 생성 작업",
            },
        ),
        migrations.AlterModelOptions(
            name="mediaasset",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "이미지 자산",
                "verbose_name_plural": "이미지 자산",
            },
        ),
        migrations.RemoveField(
            model_name="mediaasset",
            name="duration",
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="generation_prompt",
            field=models.TextField(
                blank=True,
                help_text="AI 이미지 생성에 사용된 프롬프트",
                null=True,
                verbose_name="생성 프롬프트",
            ),
        ),
        migrations.AlterField(
            model_name="generationjob",
            name="job_type",
            field=models.CharField(
                choices=[("image", "이미지 생성"), ("variation", "이미지 변형")],
                max_length=20,
                verbose_name="작업 유형",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("generated", "AI 생성"),
                    ("uploaded", "사용자 업로드"),
                    ("avatar", "프로필/아바타"),
                ],
                default="uploaded",
                max_length=20,
                verbose_name="이미지 유형",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="height",
            field=models.IntegerField(blank=True, null=True, verbose_name="세로 크기 (px)"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="width",
            field=models.IntegerField(blank=True, null=True, verbose_name="가로 크기 (px)"),
        ),
    ]
