# Generated by Django 5.2.7 on 2025-11-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="캐릭터 이름")),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("admin", "관리자"),
                            ("teacher", "교사"),
                            ("student", "학생"),
                        ],
                        max_length=20,
                        verbose_name="생성자 유형",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="캐릭터의 성격, 배경, 말투 등을 정의", verbose_name="시스템 프롬프트"
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, null=True, verbose_name="아바타 URL"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="설명"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "임시저장"),
                            ("pending", "승인대기"),
                            ("approved", "승인됨"),
                            ("rejected", "반려됨"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="승인일시"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, null=True, verbose_name="반려 사유"),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="공개 여부")),
                (
                    "school_mode",
                    models.BooleanField(
                        default=True,
                        help_text="금칙어 필터, 안전 정책 적용 여부",
                        verbose_name="School Mode 적용",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "캐릭터",
                "verbose_name_plural": "캐릭터",
                "db_table": "characters",
                "ordering": ["-created_at"],
            },
        ),
    ]
