# Generated by Django 5.2.7 on 2025-11-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="moderation_rules_ref",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="금칙어, 필터링 규칙 등",
                verbose_name="모더레이션 규칙",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="version",
            field=models.CharField(
                default="1.0",
                help_text="캐릭터 프롬프트/설정 버전",
                max_length=20,
                verbose_name="캐릭터 버전",
            ),
        ),
    ]
