# Generated by Django 5.2.8 on 2025-11-06 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0003_character_moderation_rules_ref_character_version"),
        ("organizations", "0003_classroom_classrooms_organiz_787978_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="description",
        ),
        migrations.RemoveField(
            model_name="character",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="character",
            name="moderation_rules_ref",
        ),
        migrations.RemoveField(
            model_name="character",
            name="owner_type",
        ),
        migrations.RemoveField(
            model_name="character",
            name="school_mode",
        ),
        migrations.AddField(
            model_name="character",
            name="background_story",
            field=models.TextField(
                blank=True,
                help_text="\n        출신, 경력, 과거 경험\n        예: '저는 조선시대 과학자 장영실입니다. 천문과 시계 연구에...'\n        ",
                verbose_name="배경 스토리",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="category",
            field=models.CharField(
                choices=[
                    ("educator", "교육자"),
                    ("historical", "역사인물"),
                    ("fictional", "가상인물"),
                    ("mentor", "멘토"),
                    ("friend", "친구"),
                    ("other", "기타"),
                ],
                default="educator",
                max_length=20,
                verbose_name="카테고리",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="context_length",
            field=models.IntegerField(
                default=50,
                help_text="이전 몇 턴까지 기억할지 (10~100)",
                verbose_name="대화 기억 범위 (턴)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="creativity",
            field=models.FloatField(
                default=0.7,
                help_text="0.0(결정적) ~ 1.0(창의적)",
                verbose_name="창의성 (temperature)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="example_conversations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='\n        [\n            {"user": "안녕?", "char": "*밝게 웃으며* 안녕! 오늘 기분이 어때?"},\n            {"user": "힘들어", "char": "*걱정스러운 표정으로* 무슨 일 있어? 말해봐, 들어줄게."}\n        ]\n        캐릭터의 말투를 학습할 수 있는 예시 (5개 이상 권장)\n        ',
                verbose_name="예시 대화",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="greeting_message",
            field=models.TextField(
                blank=True,
                help_text="첫 대화 시작 멘트. 예: '*방문을 열고 밝게 인사한다* 안녕! 오늘은 뭘 배우고 싶어?'",
                verbose_name="첫 대사",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="moderation_level",
            field=models.CharField(
                choices=[("low", "낮음"), ("medium", "중간"), ("high", "높음")],
                default="high",
                help_text="교육용은 높음 권장",
                max_length=20,
                verbose_name="안전 수준",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="narration_style",
            field=models.CharField(
                choices=[
                    ("none", "연출 없음"),
                    ("minimal", "최소 (*행동* 가끔)"),
                    ("novel", "소설형 (전체 서술)"),
                    ("screenplay", "시나리오형"),
                ],
                default="novel",
                help_text="소설형으로 선택하면 행동(*), 배경([]), 심리()를 자동으로 포함",
                max_length=20,
                verbose_name="연출 스타일",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="narration_template",
            field=models.TextField(
                blank=True,
                help_text="\n        행동: *별표로 감싸기*\n        배경: [대괄호로 감싸기]\n        심리: (소괄호로 감싸기)\n        ",
                verbose_name="연출 표기법",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="personality_traits",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        {\n            "core_traits": ["친절함", "유머러스", "진지함"],\n            "speech_style": "~요, ~네, 존댓말",\n            "catchphrase": "항상 응원할게!",\n            "tone": "밝고 긍정적인"\n        }\n        ',
                verbose_name="성격/특성",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="예: '수학을 사랑하는 친절한 선생님'",
                max_length=200,
                verbose_name="한 줄 설명",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="subject",
            field=models.CharField(
                choices=[
                    ("korean", "국어"),
                    ("math", "수학"),
                    ("english", "영어"),
                    ("science", "과학"),
                    ("history", "역사"),
                    ("social_studies", "사회"),
                    ("general", "일반"),
                ],
                default="general",
                max_length=20,
                verbose_name="담당 과목",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="검색용 태그. 예: ['친절', '재미있는', '초등학생용']",
                verbose_name="태그",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="teaching_style",
            field=models.TextField(
                blank=True,
                help_text="예: '소크라테스식 질문, 단계적 설명, 실생활 사례 중심'",
                verbose_name="교수법/학습 스타일",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="usage_count",
            field=models.IntegerField(default=0, verbose_name="사용 횟수"),
        ),
        migrations.AddField(
            model_name="character",
            name="visibility",
            field=models.CharField(
                choices=[("private", "비공개"), ("draft", "임시"), ("public", "공개")],
                default="private",
                max_length=20,
                verbose_name="공개 범위",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="world_setting",
            field=models.TextField(
                blank=True,
                help_text="현재 시간, 장소, 상황 등. 예: '현대 한국 서울, 고등학교 3학년 교실'",
                verbose_name="세계관/배경",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(
                help_text="예: 장영실, 수학 쌤 리사", max_length=100, verbose_name="캐릭터 이름"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters",
                to="organizations.organization",
                verbose_name="소속 조직",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="system_prompt",
            field=models.TextField(
                help_text="AI 모델에 전달될 최종 프롬프트 (자동 생성 또는 수동 편집)", verbose_name="시스템 프롬프트"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="version",
            field=models.CharField(default="1.0", max_length=20, verbose_name="버전"),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                fields=["owner", "status"], name="characters_owner_i_3eaa32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                fields=["subject", "visibility"], name="characters_subject_61c37a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                fields=["category", "visibility"], name="characters_categor_9421bb_idx"
            ),
        ),
    ]
