# Generated by Django 5.2.8 on 2025-11-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0004_remove_character_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="system_prompt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AI 모델에 전달될 최종 프롬프트 (비워두면 자동 생성됨)",
                verbose_name="시스템 프롬프트",
            ),
        ),
    ]
