# Generated by Django 5.2.8 on 2025-11-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0005_alter_character_system_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="avatar_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="아바타 URL"
            ),
        ),
    ]
