# Generated by Django 5.2.7 on 2025-11-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True, verbose_name="요약")),
                (
                    "quiz_data",
                    models.JSONField(blank=True, default=dict, verbose_name="퀴즈 데이터"),
                ),
                (
                    "pdf_url",
                    models.URLField(blank=True, null=True, verbose_name="PDF URL"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
            ],
            options={
                "verbose_name": "대화 리포트",
                "verbose_name_plural": "대화 리포트",
                "db_table": "conversation_reports",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "사용자"),
                            ("assistant", "어시스턴트"),
                            ("system", "시스템"),
                        ],
                        max_length=20,
                        verbose_name="역할",
                    ),
                ),
                ("content", models.TextField(verbose_name="메시지 내용")),
                ("tokens_used", models.IntegerField(default=0, verbose_name="사용 토큰")),
                ("filtered", models.BooleanField(default=False, verbose_name="필터링 여부")),
                (
                    "filter_reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="필터링 사유"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="메타데이터"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
            ],
            options={
                "verbose_name": "메시지",
                "verbose_name_plural": "메시지",
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="대화 제목"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="characters.character",
                        verbose_name="캐릭터",
                    ),
                ),
            ],
            options={
                "verbose_name": "대화",
                "verbose_name_plural": "대화",
                "db_table": "conversations",
                "ordering": ["-updated_at"],
            },
        ),
    ]
