# Generated by Django 5.2.7 on 2025-11-05 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0003_character_moderation_rules_ref_character_version"),
        ("conversations", "0003_initial"),
        ("organizations", "0003_classroom_classrooms_organiz_787978_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="tokens_used",
        ),
        migrations.AddField(
            model_name="conversation",
            name="policy_snapshot_ref",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="대화 생성 시점의 School Mode 정책",
                verbose_name="정책 스냅샷",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="대화의 주제나 목적",
                max_length=200,
                null=True,
                verbose_name="대화 주제",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="citations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="응답에 사용된 참고 자료",
                verbose_name="인용/출처",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="error_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="오류 코드"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="model_version",
            field=models.CharField(
                blank=True,
                help_text="사용된 AI 모델 버전 (예: gpt-4, gpt-3.5-turbo)",
                max_length=100,
                null=True,
                verbose_name="모델 버전",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="prompt_hash",
            field=models.CharField(
                blank=True,
                help_text="프롬프트 무결성 검증용",
                max_length=64,
                null=True,
                verbose_name="프롬프트 해시",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="retry_count",
            field=models.IntegerField(default=0, verbose_name="재시도 횟수"),
        ),
        migrations.AddField(
            model_name="message",
            name="safety_status",
            field=models.CharField(
                blank=True,
                help_text="safe, flagged, blocked 등",
                max_length=50,
                null=True,
                verbose_name="안전 상태",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="token_usage",
            field=models.IntegerField(default=0, verbose_name="토큰 사용량"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "created_at"], name="conversatio_user_id_a2c0bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["classroom", "created_at"],
                name="conversatio_classro_985342_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["character", "created_at"],
                name="conversatio_charact_de46cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="messages_convers_3ebb41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["role", "created_at"], name="messages_role_c5c560_idx"
            ),
        ),
    ]
