# Generated by Django 5.2.7 on 2025-11-05 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="enrolled_classrooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="학생들",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_classrooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="담당 교사",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="organizations.organization",
                verbose_name="소속 조직",
            ),
        ),
    ]
