# Generated by Django 5.2.7 on 2025-11-05 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["organization", "is_active"],
                name="classrooms_organiz_787978_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["teacher", "is_active"], name="classrooms_teacher_f5848e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["type", "region"], name="organizatio_type_77d41f_idx"
            ),
        ),
    ]
